services:
  - type: web
    name: blazegraph
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 10000
      - key: JAVA_OPTS
        value: "-Xmx512m -XX:+UseG1GC"
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    healthCheckPath: /blazegraph/#query
    healthCheckTimeout: 300