services:
  - type: web
    name: blazegraph
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 10000
    healthCheckPath: /blazegraph/#query
    disk:
      name: data
      mountPath: /data
      sizeGB: 1